### ISSUE TITLE
Naming (is hard)

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/fable-browser#1]
Following discussion from https://github.com/elmish/react/pull/34#issuecomment-457096866

> Another question about the naming is: is there any benefits for adding Fable. to the namespace ? If we want something simple I would name the package Fable.Browser and have the top module be Browser.

I think this makes sense, we can start the names of packages in this repository with `Fable.Browser.` but the namespace only with `Browser.`.

Other questions:

- Put interfaces always directly in the `Browser` namespace? This can be done no matter the name of the package, and there shouldn't be name conflicts. The exceptions could be specialized interfaces that we don't want to open by default (e.g. workers).
- Values need to be in a module, but should we `AutoOpen` them (except for workers)? This way the name of the module/package (Dom, Svg, File, Clipboard, WebSocket) is not very important, because just by opening or qualifying `Browser` users will already have access to global values.
- Move `Console` to its own package. MDN includes `Window` in [the DOM Api](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) so it should be ok to keep it here. But moving `Console` to a different package, we could add it as a dependency in the WebWorker package without having to depend on the rest of the DOM interfaces.

> In principle, [Node has its own Console object](https://github.com/fable-compiler/fable-import/blob/0f780da448be900287f1a0bd1af9a59fdc7680d4/Node/Base.fs#L8) so we shouldn't need to worry about that, but if we put Console in a non-browser package (outside of this repository) we could share it with the next Node bindings too. Although in that case, I'm not sure what namespace we should use for Console 🤔

**Comment by Zaid-Ajaj** [comment]
Commented on the issue here https://github.com/elmish/react/pull/34#issuecomment-457128690

**Comment by MangelMaxime** [comment]
We should keep the discussion here. The PR is about `elmish/react` and should not be related to discussing how to name things. :)

> > And I thought it could be a good opportunity to drop the Fable.Import (and Fable.Helpers) prefix and have smaller packages in their own repository for easier maintenance
> 
> ❤️ Finally! having to always open these was always confusing and distracting: one namespace has types so I need `Import` for the signatures and the other has code so you need `Helpers` as well (very generic name, too many libraries have it) not to mention opening nested modules: (e.g. `Fable.Import.React.Props`)
> 
> Although I agree with @MangelMaxime that `Fable.Browser.Dom` doesn't really make sense.
> 
> IMO that the following is much cleaner:
> 
>     * `Fable.Browser` as the package name _and_ the namespace  (easy to find on nuget)
> 
>     * `Browser` is the _auto-opened_ module to use to work with browser API's  when someone opens the namspace `Fable.Browser`.
> 
> 
> Library code:
> 
> ```fsharp
> namespace Fable.Browser 
> 
> [<AutoOpen>] 
> module Browser = 
>   type Document = 
>       let getElementById : elementId: string -> HTMLElement
> 
>   let [<Global>] document: Document = jsNative
> ```
> 
> Here is how the consuming code looks like:
> 
> ```fsharp
> open Fable.Browser
> 
> let rootElem = document.getElementById "root"
> 
> console.log("hello from Fable")
> ```
> 
> So much easier to think about, you need to work with the dom? just open the browser namespace and you are good to go
> 
> Another thing I am not sure of is whether to add the types in a different module (e.g. `Types`) or just leave them in `Browser` (as in the example above). Let me explain concretely:
> this is the alternative library binding code:
> 
> ```fsharp
> namespace Fable.Browser 
> 
> [<RequireQualifiedAccess>]
> module Types = 
>   type Document = 
>       let getElementById : elementId: string -> HTMLElement
> 
> [<AutoOpen>] 
> module Browser = 
>   let [<Global>] document: Types.Document = jsNative
> ```
> 
> this way, if the consumer code wants to use explicit type signatures, they won't have to open _yet_ another namespace but instead, qualify the type name with prefix `Types`:
> 
> ```fsharp
> open Fable.Browser
> 
> // qualify type names if you need them
> let init (doc: Types.Document) : unit = 
>    let root = doc.getElementById "root"
>    root.innerHTML <- "Hello from F#"
> 
> 
> init document // document is available since Browser is auto opened
> ```
> 
> the nice about this, is that if the user uses many binding libraries with `Types`, then he can just re-use the `Types` module that includes the types from a different namespace:
> 
> ```fsharp
> open Fable.React
> open Fable.Brower
> 
> // use types from Fable.React
> let makeStyle (x: Types.ICSSProp list) = 
>   // do stuff 
> 
> // qualify type names from Fable.Browser
> let init (doc: Types.Document) : unit = 
>    let root = doc.getElementById "root"
>    root.innerHTML <- "Hello from F#"
> ```
> 
> What do you think @alfonsogarciacaro @MangelMaxime ??

**Comment by MangelMaxime** [comment]
> The only issue is if you want to qualify a value you need to remember the name of the module (as in Dom.window).

What do you mean by qualify?  I would expect people to either use:

```fs
open Browser

window.addEventListener //...
performance.now()
```

or 

```fs
Browser.window.addEventListener //...
Browser.performance.now()
```

Well, of course, people could use 

```fs
Browser.Dom.window.addEventListener //...
Browser.Performance.performance.now()
```

The API isn't that bad, but I am not sure it would add value for them to use this API compare to the others proposed before. The API that I called "Zaid's version" and "Maxime's version" in my previous post is what I see 90%+ of the time in people code.

------------------

One thing that surprise when looking at the current implementation of `Fable.Browser.Dom` package is that `namespace Browser.Types` is defined several times in different files. Does F# support that? Or Fable? 

I remember having an error like `FSHARP: A namespace and a module named 'Fable.C3' both occur in two parts of this assembly` in the past when declaring a namespace or module several types.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Ah yes, you are right. I guess if we don't `open Browser` then `Dom` isn't "auto opened".

Currently is fine/ok I guess. It still provides a clean middle ground between both ways.

**Comment by alfonsogarciacaro** [comment]
So it's the current proposal OK for everybody? If there're no other suggestions we can start rolling out the new packages.

**Comment by chadunit** [comment]
How about `Fable.Browser.Core` or just `Fable.Browser` for the "main" package name instead of `Fable.Browser.Dom`? (If highlighting "DOM" is important, then it can still be put in the package description.)

It would convey package organization based on usage/practicality rather than ambiguous spec interpretation which seems already rather loosely followed, e.g. it was mentioned that `Window` is included because it is referenced by MDN DOM page, but so is `Event` and that got its own package.

**Comment by alfonsogarciacaro** [comment]
@chadunit The problem with naming is the discussions never end because everybody has a different opinion and usually most of the arguments are also valid :) Given that the beta packages are already pushed, I'd prefer no to modify them unless there's a very strong reason for that, even if the structure is not perfect (I doubt it will ever be).

However, it's also true we haven't adapted yet the most used packages (Fable.React, Elmish, etc) so if you want to take ownership of these packages and maintain them (which would make me very happy) you're free to choose the name you prefer 😄

**Comment by chadunit** [comment]
No worries (should issue be closed?). Pretty sure I would be a terrible maintainer overall so I will have to decline to volunteer to take over just to change the name. 😺

**Comment by alfonsogarciacaro** [comment]
Elmish and other packages have already started to roll out updates compatibles with the new Fable.Browser packages so we can indeed close this :)
