### ISSUE TITLE
Support for IntersectionObserver

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/fable-browser#105]
I've had a good search and cannot find bindings for [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API);   am I correct in concluding that it's not yet supported?

I'd be willing to submit a PR if it's not already implemented

**Comment by MangelMaxime** [comment]
Indeed it seems like the API is not implemented yet.

**Comment by davedawkins** [comment]
Gentle reminder that a PR for this API has been submitted. I'm using a local copy of the API for now, so I'm ok

**Comment by MangelMaxime** [comment]
Thank you for the PR, package has been published
