### ISSUE TITLE
blob.text() and file.text() missing?

### ISSUE THREAD

**Issue by njlr** [fable-compiler/fable-browser#106]
`Blob` and `File` should have a method called `text` that returns `Promise<string>`, but this appears to be missing?

**Bindings**

 * https://github.com/fable-compiler/fable-browser/blob/master/src/Blob/Browser.Blob.fs#L18-L22
 * https://github.com/fable-compiler/fable-browser/blob/master/src/Dom/Browser.File.fs#L15-L18

**API Reference**

 * https://developer.mozilla.org/en-US/docs/Web/API/Blob/text
 * https://developer.mozilla.org/en-US/docs/Web/API/File

Happy to send a PR!

**Comment by MangelMaxime** [comment]
Thank you for the report, a new version of the package has been published.
