### ISSUE TITLE
addEventListener_xyz seems to be missing

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/fable-browser#11]
The new api seems to only have one ``addEventListener(string, Event->unit)``.

The old api had this generic method, and other specialised ones like ``addEventListener_click(MouseEvent->unit)``.

This was really nice because you didn't have any magic strings, and you had a bit more type safety because the handler got a MouseEvent, not just a generic Event.

Were these removed on purpose? Is there a chance to add them back?

**Comment by MangelMaxime** [comment]
Hello, they were removed on purpose in order to make the life of the IDE easier.

Before `Fable.Import.browser` was a single file with  12000 lines and most IDE had a hard time with that.

> Is there a chance to add them back?

I don't think sorry.

**Comment by alfonsogarciacaro** [comment]
Yes, as Maxime says, the main purpose of the package split was to make the code more manageable reducing the number of lines to maintain. Also, the specialized extensions relied on the `Emit` attribute which added a lot of weight to the .dll and we wanted to reduce that for the REPL.

But I acknowledge they were useful. It could be possible to create an extra package for them using type extensions. I can create a first version of such package, but I'd need someone else to publish and maintain it. Would you volunteer? :)

**Comment by 0x53A** [comment]
> Would you volunteer?

Sure, I can give it a try. Looks like a relatively easy first fable lib.

> I can create a first version of such package

I mean if you want to I won't say no, but I think I can just clone this repo (for the build infrastructure etc) and add the one project to src?

What are your thoughts on naming?

``fable-browser-ext`` for the repo, ``Fable.Browser.Dom.Ext`` for the package?

**Comment by 0x53A** [comment]
I wanted to see how the build works, but https://github.com/fable-compiler/fable-publish-utils/ 404s for me.

Is the repository private, or was it renamed?

**Comment by alfonsogarciacaro** [comment]
Sorry, I moved the package to Fable repo: https://github.com/fable-compiler/Fable/tree/master/src/fable-publish-utils

I've created a first version of the package here, by copying some of the specialized methods in `Document` type from the old fable-import: https://github.com/alfonsogarciacaro/fable-browser-dom-ext/

I invited you for collaboration but probably it's better to move it to your profile. My main doubt is about the namespace. Depends on how you want to activate the extension, by opening `Browser` or `Browser.Types`.

**Comment by 0x53A** [comment]
Thank you!

> [...]  but probably it's better to move it to your profile

Done: https://github.com/0x53A/fable-browser-ext
Are you ok with the package name ``Fable.Browser.Dom.Ext`` or should I prefix it?


> My main doubt is about the namespace. Depends on how you want to activate the extension, by opening Browser or Browser.Types.

I think I would keep it ``Browser`` like in your version, unless this causes any issues? (The only issue might be that it populates intellisense)

**Comment by alfonsogarciacaro** [comment]
Cool, thanks! :clap:

I think the name is fine 😸 About the namespace, it shouldn't cause any issues. I was just thinking in the case where users only open `Browser.Types`, but it should probably be fine.

**Comment by 0x53A** [comment]
Is there a trick to convert it from

```f#
[<Emit("$0.addEventListener('pointermove',$1...)")>] abstract addEventListener_pointermove: listener: (PointerEvent -> 'Out) * ?useCapture: bool -> unit
```

to

```f#
[<Emit("$0.addEventListener('pointermove',$1...)")>] member addEventListener_pointermove(listener: (PointerEvent -> 'Out), ?useCapture) = jsnative
```

or did you do that by hand?

-------------

I've setup auto-publish through appveyor when a new tag with the pattern ``release-a.b.c`` or ``prerelease-x.y.z-beta.4`` is created.

**Comment by MangelMaxime** [comment]
@0x53A If you use VSCode and the members are similarly structured you can use multi-cursor to update the code.

**Comment by 0x53A** [comment]
I've published [Fable.Browser.Dom.Ext](https://www.nuget.org/packages/Fable.Browser.Dom.Ext) with type extensions for ``Document``, ``Element``, ``HTMLElement`` and ``Window``. That should cover ~80%.

I'll do the rest either when I need it myself, or on request. Feel free to open an issue :D

Thanks.
