### ISSUE TITLE
uint64 properties in MediaRecorderOptions not working with Fable 4

### ISSUE THREAD

**Issue by kerams** [fable-compiler/fable-browser#118]
```fsharp
let o = createEmpty<MediaRecorderOptions>
o.audioBitsPerSecond <- 48_000UL
o.mimeType <- mimeType
let recorder = MediaRecorder.Create (stream, o)
```

This used to work for me in the past (pre Fable 4). However, now I'm getting `TypeError: Cannot convert a BigInt value to a number` on the last line. If I do `!!48_000`, the snippet works fine.

I wonder whether the properties in `MediaRecorderOptions` and `MediaRecorder` (and possibly elsewhere) shouldn't be changed to simple `int`. These properties don't need the `int64` range, and the unsigned restriction feels merely cosmetic in any Fable code. It would be a breaking change, albeit on a less common API, but better that than unexpected runtime failures.

**Comment by MangelMaxime** [comment]
> I wonder whether the properties in MediaRecorderOptions and MediaRecorder (and possibly elsewhere) shouldn't be changed to simple int. These properties don't need the int64 range, and the unsigned restriction feels merely cosmetic in any Fable code. It would be a breaking change, albeit on a less common API, but better that than unexpected runtime failures.

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder/audioBitsPerSecond), the accepted value is `A Number (unsigned long).`

I think what caused the breaking change at runtime is that since Fable 4.0.5, Fable now use "native JS BigInt for int64/uint64" when before it was using custom code.

**Comment by kerams** [comment]
Indeed.

> (unsigned long)

While we can translate this to a `uint64` constraint in F#, in JS it's just a hint that the number should be positive. The type is still `Number`.

I like the fact that Fable dropped its `long` implementation for native bigints, but if an API like this works with large integers, we're now forced to use `float` in type annotations, unless there's a solution I am missing. It's a bit unfortunate, but at the end of the day I am fine with the tradeoff.

**Comment by MangelMaxime** [comment]
I merged your PR.

But now I think double thinking perhaps, I should have waited for @alfonsogarciacaro opinion.

I think there 2 ways of seeing the situation:

1. Prefer to avoid custom implementation and reduce bundle size -> This means using native bigint for int64 and uint64
2. Prefer F# correctness and so in this case disguise int64 and uint64 as a number using a custom implementation which increase the bundle size

I am not sure what is the preferred position from Fable side here.

Ping @alfonsogarciacaro @ncave

**Comment by ncave** [comment]
@MangelMaxime I think it's a good change, IMO the original binding was wrong.

MDN says `A Number (unsigned long)`, not `A Number (unsigned long long)`, so 32 bits, not 64 bits.
See `ULONG_MAX` in [integer limits](https://learn.microsoft.com/en-us/cpp/cpp/integer-limits).
