### ISSUE TITLE
Contributing bindings for ResizeObserver

### ISSUE THREAD

**Issue by robitar** [fable-compiler/fable-browser#122]
I'm assuming they don't exist yet, or at least I couldn't find them, so I've set up some bindings. Thankfully, they are almost identical to IntersectionObserver, so it should be quite consistent.

It seems like a good opportunity to make a first contribution! Should I just open a pull request? Are there any steps to take?

**Comment by MangelMaxime** [comment]
Hello @robitar,

No additional steps are required here, you can send a PR to this repo and a maintainer will review it. If you are stuck, feel free to ask questions :).
