### ISSUE TITLE
Wrong type in DataTransfer object

### ISSUE THREAD

**Issue by M-Mueller** [fable-compiler/fable-browser#128]
The following code compiles but then fails during runtime in Firefox:
```fs
open Fable
open Browser.Dom

let div = document.getElementById("mydiv")

div.addEventListener("dragover", fun e -> 
    let e = unbox<Browser.Types.DragEvent> e

    if e.dataTransfer.types.contains("test") then
        console.log("CONTAINS")
    else
        console.log("NOT CONTAINS") 
    ()
)
```
The runtime error is:
```
Uncaught TypeError: e_1.dataTransfer.types.contains is not a function
```

[Repl](https://fable.io/repl/#?code=PTAEHUCcEsBcFNQGMD2ATRLKgDYoIZqj6gDO+AtgA46IBmkKFZ0GARvpAFApXwB2oAGL42tHn0EAhRgHdS8SADoAIky5dasUGmgA3UAF4dKJAFcKA2EoDm8WAFFal-rCkBPAJJoAFACIKd109PwBKDWClQjQHPSsAGWhSBH5FfzRIfBsUOMg-ABpQOjNBRABaAD5QLlBa3HtQRGMSthQADwAeGRR5RSUAFXc+UlVMm1irKvgNOtBoOkalNHxYfH7M-lI6Ptgh+BHUV3xoTf8EZLDQWAALARrZusPSFFolPBt-AGEAeQA5foAgp5fgBlML3WrwHAKCEPJ4veBvFAfPy-b79UA-f5A0GXWE+cKhIA&html=DwEwlgbgBCBOCGBzR8BGAbApgXgEQBdYBXTXAPgBEFEp8ALMAZ2AHpwIyAoUSKMEPAFsAnu3JUkUAPYRMsKHTmZW7MkA&css=Q)

`DataTransfer.types` is defined in Fable as [DomStringList](https://github.com/fable-compiler/fable-browser/blob/master/src/Dom/Browser.Dom.fs#L2949), but during runtime it's a regular `Array` of strings. If I unbox `types` like this it works:
```fs
let types = unbox<string array> e.dataTransfer.types
```

Is this a bug in Fable or I'm I using this wrong?

**Comment by MangelMaxime** [comment]
Hello,

Thanks you for the report.

Indeed, in JavaScript it seems to be "readonly array of string". I changed the signature to F# array as they are immutable and seems to be working fine in your test.

If the issue is not solved with the new release, feel free to re-open.

**Comment by M-Mueller** [comment]
Thank you for the quick fix!
