### ISSUE TITLE
Port Position  (Geoposition) from Fable.Import

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-browser#13]
https://github.com/fable-compiler/fable-import/blob/master/Browser/Fable.Import.Browser.fs#L7065

**Comment by alfonsogarciacaro** [comment]
Well, one of the reasons to split the browser package and reduce the number of exposed types was to make it easier to maintain the bindings, but if I end up moving here all the types from Fable.Import.Browser and I remain as the sole maintainer the situation will be the same as before :)

My suggestion is:

- If you only need one or a few types from Fable.Import.Browser, just copy them to your library and expose them as `[<Global>]` if necessary.
- If you need more comprehensive bindings for [a specific Web API](https://developer.mozilla.org/en-US/docs/Web/API), publish a package ideally following the structure of the packages in this repo.

**Comment by forki** [comment]
The problem with moving it to the maps component itself is that it will clash with different components that all bring their own Geoposition

**Comment by alfonsogarciacaro** [comment]
Then we go on to suggestion number 2: somebody can create a package for the Geolocation Web API and become the maintainer :)

**Comment by MangelMaxime** [comment]
Fable.Browser.Geolocation seems to include the change requested by this issue.

My only problem with how it's done is that it is removing the Geolocation prefix on the types.

For example, `PositionError` doesn't exist it should be `GeolocationPositionError` etc.

I am letting it like that for now, and we will see if someone complains about it or send a PR to fix it.

**Comment by MangelMaxime** [comment]
I re-open in fact, not following strictly the JavaScript API names will cause a problem for the libraries which will depend on the types.

Indeed, when converting the library via ts2fable it will have the suffix in the type name.
