### ISSUE TITLE
Add support for EventSource API

### ISSUE THREAD

**Issue by gabrieldavid98** [fable-compiler/fable-browser#134]
Hi everyone, 

I was looking at the code and I realized, Fable does not have bindings for [EventSource API](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) (Am I mistaken?). I'm working on a PR to add it, but not really sure if it is the right way to do it, since EventSource is similar to WebSockets I harnessed some code from that module and adjust it to meet EventSource needs, I'm going to send the PR and see what you guys have in mind to make it better. Thanks

Greetings

**Comment by MangelMaxime** [comment]
Hello,

Indeed it seems to be missing. I think creating a new package like done for WebSocket is the way to go ATM.

**Comment by MangelMaxime** [comment]
Thanks for the PR, I released the package on NuGet.

**Comment by gabrieldavid98** [comment]
Hey, no problem, thanks for the release.
