### ISSUE TITLE
ServiceWorkerContainer:register should accept URL as well as string

### ISSUE THREAD

**Issue by joprice** [fable-compiler/fable-browser#141]
The typescript types at `@types/serviceworker` accept a URL as well as a string:

```ts
interface ServiceWorkerContainer extends EventTarget {
  ...
  register(scriptURL: string | URL, options?: RegistrationOptions): Promise<ServiceWorkerRegistration>;
```

Whereas the current bindings only take a string:

https://github.com/fable-compiler/fable-browser/blob/8300b75f1d80f4fc8f787c5815f11b3c41238688/src/Worker/Browser.Worker.fs#L75

**Comment by MangelMaxime** [comment]
This should be fixed in 1.4.0
