### ISSUE TITLE
Information about method extensions

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-browser#19]
I am using/testing `Fable.Browser.Css` in one of my projects and discover something.

In order to get the method extensions working, I need to manually open the module [Browser.CssExtensions](https://github.com/fable-compiler/fable-browser/blob/master/src/Css/Browser.Css.Ext.fs#L2)

Otherwise, the extensions are not working.

```fs
Browser.Dom.document.styleSheets // Error

open Browser.CssExtensions

Browser.Dom.document.styleSheets // Ok
```

So should we remove `[<AutoOpen>]` so people know don't expect it to be working out of the box?

I suspect it will be the same for all the other method extension.

PS: I think `AutoOpen` needs you to open part of the namespace in order to work.

**Comment by alfonsogarciacaro** [comment]
It's not very intuitive, but `AutoOpen` **only opens the module**, which means it won't open until you open the namespace. If you `open Browser` it should work:

```fsharp
Browser.Dom.document.styleSheets // Error

open Browser

// Browser.Dom is opened too

document.styleSheets // Ok
```

**Comment by MangelMaxime** [comment]
You are right
