### ISSUE TITLE
missing types MediaStreamConstraints, NavigatorUserMediaSuccessCallback, NavigatorUserMediaErrorCallback

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/fable-browser#2]
references https://github.com/fable-compiler/ts2fable/issues/290

--------------

babylonjs contains this:

```ts
interface Navigator {
    mozGetVRDevices: (any: any) => any;
    webkitGetUserMedia(constraints: MediaStreamConstraints, successCallback: NavigatorUserMediaSuccessCallback, errorCallback: NavigatorUserMediaErrorCallback): void;
    mozGetUserMedia(constraints: MediaStreamConstraints, successCallback: NavigatorUserMediaSuccessCallback, errorCallback: NavigatorUserMediaErrorCallback): void;
    msGetUserMedia(constraints: MediaStreamConstraints, successCallback: NavigatorUserMediaSuccessCallback, errorCallback: NavigatorUserMediaErrorCallback): void;
    webkitGetGamepads(): Gamepad[];
    msGetGamepads(): Gamepad[];
    webkitGamepads(): Gamepad[];
}
```

That causes an error:

![grafik](https://user-images.githubusercontent.com/4236651/53042030-aa104b00-3485-11e9-9f16-2958c2f6b2e9.png)

If I F12 on ``MediaStreamConstraints`` in Visual Studio in the babylon.d.ts file, I go to ``C:\Program Files (x86)\Microsoft SDKs\TypeScript\2.8\lib.dom.d.ts``.

So I think these types need to be added to ``Fable.Import.Browser``.

-----------------

Note: I'm not sure if this is even the right repository.

Intellisense shows there is apparently already a type ``MediaStream``, but I can't find that anywhere?
![grafik](https://user-images.githubusercontent.com/4236651/53042708-34a57a00-3487-11e9-9e84-445ac89217fd.png)

**Comment by whitetigle** [comment]
yes it seems the types do not exist yet in [Fable.Import.Browser](https://github.com/fable-compiler/fable-import/blob/master/Browser/Fable.Import.Browser.fs#L6536).

`MediaStream` exists [here](https://github.com/fable-compiler/fable-import/blob/master/Browser/Fable.Import.Browser.fs#L6334).

**Comment by 0x53A** [comment]
weird, github search seems to be broken:

![grafik](https://user-images.githubusercontent.com/4236651/53091570-9232d880-3512-11e9-994b-51f1430325c6.png)

------

thank you, I have moved the issue: https://github.com/fable-compiler/fable-import/issues/79

**Comment by Titaye** [comment]
Fable.Browser.MediaStream package should resolve this issue
```fsharp

let getStream () =
    StreamContraints.Create(true, true)
    |> mediaDevices.getUserMedia
```

**Comment by MangelMaxime** [comment]
Fixed in Fable.Browser.MediaStream 2.0.0
