### ISSUE TITLE
Missing bindings for WebSockets and DataView

### ISSUE THREAD

**Issue by codec-abc** [fable-compiler/fable-browser#20]
Hi,

I have started playing (again) with Fable.
Among other things, I want, this time to experiment with [WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket) . As I want to read binary from it I also want to use [DataView](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/DataView).

It may be me, but I did not manage to find bindings for those types.

Thanks to Fable I was able to use an weakly typed escape hatch to get my stuff working, but it would be better, imho, that we have support for those APIs out of the box.

What is your opinion on the matter?

Regards

**Comment by alfonsogarciacaro** [comment]
Hi @codec-abc! About websockets, there `Fable.Browser.WebSocket` is already published. Please give it a try and if you find something missing, it'd be great if you could [send a PR](https://github.com/fable-compiler/fable-browser/blob/master/src/WebSocket/Browser.WebSocket.fs).

About DataView, I tried to unify F# numeric arrays and JS typed arrays in Fable.Core 3 for simplicity but unfortunately a few things were missing. There's a similar issue here: https://github.com/fable-compiler/Fable/issues/1858 I basically need to gather the things that are missing and make a new release of Fable.Core, but you can also create port the [old binding](https://github.com/fable-compiler/Fable/blob/807e03b8b9e8fb30d73fff1ca4cca1ce3d0ea77b/src/dotnet/Fable.Core/Fable.Import.JS.fs#L507-L530) to your project if you need it now.

You can find more info about the reasoning behind the changes in Fable.Core 3 and splitting some packages in [this blog post](https://fable.io/blog/Announcing-2-2.html).

**Comment by codec-abc** [comment]
Thanks for the answer. Very much appreciated.
Also, thanks for pointing out the WebSocket package that I missed. It seems pretty suited for my needs.
For the JS array, I will use the emit attribute and two small functions for now. While, a bit dirty it is the easiest solution  for now.
