### ISSUE TITLE
Missing FormData.create() call?

### ISSUE THREAD

**Issue by danyx23** [fable-compiler/fable-browser#22]
I may have missed something but it looks like the bindings in this repo only define the inteface for FormData and FormDataType but provide no implementation. Fable.SimpleHttp contains the following snippet:
```fsharp
[<Emit("new FormData()")>]
    /// Creates a new FormData object
    let create() : FormData = jsNative
```
Should this maybe be moved into fable-browser so that this functionality is available for plain fable projects without an external dependency or the need to declare this yourself?

**Comment by alfonsogarciacaro** [comment]
Hi @danyx23! A tricky thing of the bindings is we need to use interfaces also for the static part of the type (including the constructor) to prevent [Fable mangling](https://fable.io/docs/communicate/fable-from-js.html#Name-mangling). The common pattern is to add the `-Type` suffix to the static part and then expose it using the name of the type (without the suffix): https://github.com/fable-compiler/fable-browser/blob/e9f537fed9b4eea427b8d2fb159728af3420496a/src/XMLHttpRequest/Browser.XMLHttpRequest.fs#L44-L66

So if you reference the `Fable.Browser.XMLHttpRequest` (note it's in its own package) and `open Browser`, you should be able to run `FormData.Create()` to get a new instance of FormData.

**Comment by danyx23** [comment]
Ah, this works! Thanks for pointing that out!
