### ISSUE TITLE
Binding for `getComputedStyle` should be on `window` not on `document`?

### ISSUE THREAD

**Issue by matthid** [fable-compiler/fable-browser#28]
Apparently, it is part of `window` not part of `document`? See
https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

https://github.com/fable-compiler/fable-browser/blob/8c3073bd5bf45ae2d997e9a1b2abc18a093ba85b/src/Css/Browser.Css.Ext.fs#L7-L16

**Comment by alfonsogarciacaro** [comment]
Good catch! ⚾️ Could you please send a PR to fix it?

**Comment by matthid** [comment]
Sure, I just wanted to verify I understood the problem correctly. Please remind if I forget about it

**Comment by MangelMaxime** [comment]
Released in Fable.Browser.Css 2.0.0
