### ISSUE TITLE
Missing Element.closest(selector)

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-browser#3]
[Element](https://github.com/fable-compiler/fable-browser/blob/414778fa300e7467a55b73763517a1991d7438ee/src/Dom/Browser.Dom.fs#L419) is missing `closest(selector)` member.

[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest)

I propose to add it with the form:

```fs
 abstract closest: selectors : string -> Element option
 abstract closest: element : Element -> Element option
```

`Element option` inform the user that this function can return `null`

**Comment by alfonsogarciacaro** [comment]
Looks good, can you please send a PR? Thanks!
