### ISSUE TITLE
Any plans for adding MediaQueryList support

### ISSUE THREAD

**Issue by thitemple** [fable-compiler/fable-browser#33]
I saw that this is commented out in the code

https://github.com/fable-compiler/fable-browser/blob/bdb5c60657411dac5029b53d475938c25988c65d/src/Dom/Browser.Dom.fs#L823

Any plans to adding it?

**Comment by MangelMaxime** [comment]
Hello, you can add the package `Fable.Browser.MediaQueryList` to your project and you should get access to this API.

You can use it like that:

```fs
open Fable.Core
open Browser.Types
open Browser.Dom

let mql = window.matchMedia("(max-width: 600px)")

mql.addEventListener("change", (fun ev -> 
    let ev = ev :?> MediaQueryList
    if ev.matches then
        printfn "less"
    else
        printfn "more"
))
```

**Comment by thitemple** [comment]
thanks, I didn't know there was such project

**Comment by MangelMaxime** [comment]
@thitemple Oh, it only exists since yesterday because I created it to answer your request :)

**Comment by thitemple** [comment]
Am I missing something? 
I created new classlib projetct to test it install the new package:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Browser.MediaQueryList" Version="1.0.0" />
  </ItemGroup>

</Project>
```
And this is the result:

![image](https://user-images.githubusercontent.com/368734/80049999-747c4d00-84e2-11ea-9e94-86851d486349.png)

**Comment by MangelMaxime** [comment]
It seems like even if the [module](https://github.com/fable-compiler/fable-browser/blob/0b2a98f58db7e5808659d94c65569cd77491447d/src/MediaQueryList/Browser.MediaQueryList.Ext.fs#L1-L2) is marked as `AutoOpen` you need to `open Browser` in order for it to kick in.

*There is an error in the module name, I will release a new version to fix the copy/paste error*

So you have to write:

````fs
module Say =
    open Browser
    let mql = window.matchMedia("")
```
