### ISSUE TITLE
DataTransfer properties are not settable

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/fable-browser#35]
DataTransfer property getters are there, but are missing setters: https://github.com/fable-compiler/fable-browser/blob/bdb5c60657411dac5029b53d475938c25988c65d/src/Dom/Browser.Dom.fs#L2826-L2834

The deprecated Fable.Import has them:
https://github.com/fable-compiler/fable-import/blob/master/Browser/Fable.Import.Browser.fs#L1553-L1561

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @jwosty :+1: Would it be possible to send a PR to fix it? Thanks!
