### ISSUE TITLE
When will the package be ready for stable release?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/fable-browser#4]
I assume that *alpha* means experimental but what exactly needs to be tested until the stable release?

**Comment by alfonsogarciacaro** [comment]
Currently, the plan is more or less like:

- Push Fable.Core 3 beta: Done, besides some additions and API cleaning the main breaking change is renaming `Fable.Import.JS` to `Fable.Core.JS`.
- Update most used packages to Fable.Core 3 and Fable.Browser.XXX: In process, I'm trying to do it myself for Elmish, I'll ask you and the other maintainers for the other ones :)
- Try the new packages in a couple of production projects
- Announce the release of the new packages (probably together with fable-compiler 2.2 stable and fable-compiler-js 1.0) explaining the new name structure.

**Comment by Zaid-Ajaj** [comment]
Thanks a lot for the clarification Alfonso! 

> Update most used packages to Fable.Core 3 and Fable.Browser.XXX: In process, I'm trying to do it myself for Elmish, I'll ask you and the other maintainers for the other ones :)

I have to say that I am bit reluctant to updating all the packages to Fable.Core 3 beta just to update them all again when the packages become stable. I was thinking of waiting for the stable release but this kind of defeats the purpose of having them published as beta in the first place 

I will update soon, just putting it out there that this *very* time consuming (maybe I shouldn't have wrote so many of them haha 😅) 

That said, I also wanted to mention that I am very happy with Fable supporting nuget and being published to npm, very simple config files, easy package installations and easy to think about, just `npm install && npm start` and everything is ready to go :tada:

**Comment by alfonsogarciacaro** [comment]
> I have to say that I am bit reluctant to updating all the packages to Fable.Core 3 beta just to update them all again when the packages become stable.

If I'm not mistaken, you shouldn't need to publish the packages again when the "stable" versions come out, Nuget/Paket will just prefer the stable version even if you have a dependency on the prerelease.

> Just putting it out there that this very time consuming.

Yeah, sorry about that. Let me know if I can do something to help. In most cases you should only need to changes a few `open` statements to update the dependencies. Also, I didn't express myself properly, you don't need to update all your packages just yet. But to test in my production projects (point 3 in the roadmap above) I need at least elmish-react, elmish-browser and thoth-json updated, that's why I'm still waiting a bit to release _stablish_ versions.

**Comment by Zaid-Ajaj** [comment]
> Yeah, sorry about that. Let me know if I can do something to help

No worries, it should be doable, I just need to make some time for it :smile: 

>  But to test in my production projects (point 3 in the roadmap above) I need at least elmish-react, elmish-browser and thoth-json updated, that's why I'm still waiting a bit to release stablish versions.

I see, then for now I will publish just the most common ones too 👌

**Comment by MangelMaxime** [comment]
> But to test in my production projects (point 3 in the roadmap above) I need at least elmish-react, elmish-browser and thoth-json updated

Yes yes it's coming :p :p
