### ISSUE TITLE
Fable.Browser.Dom depends on prerelease of FSharp.Core

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-browser#48]
Fable.Browser.Dom (2.1.1)
      FSharp.Core (>= 5.0.0-beta.20475.4)

I assume that was a mistake

**Comment by alfonsogarciacaro** [comment]
Ups, yeah, probably when doing the latest release I used the dotnet 5 preview by mistake. We need a global.json file in this repo. Thansk!

**Comment by alfonsogarciacaro** [comment]
Hopefully fixed with 2.1.2 release, please reopen if there's still a problem 👍
