### ISSUE TITLE
Clipboard API event handler argument types are incorrect

### ISSUE THREAD

**Issue by kodfodrasz** [fable-compiler/fable-browser#56]
Dear Fable team,

I'm fairly new to Fable, just trying it out, but while experimenting with it I encountered a problem in the clipboard API (the old one, not Navigator based) : the argument types of the event handlers were for DragEvent but the MDN docs suggested ClipboardEvent should be expected.

I created a PR (#55 ) with a suggested solution.

Best Regards,
@kodfodrasz

**Comment by kodfodrasz** [comment]
Also I have noticed that the event handler properties for clipboard events are missing from Document. I have added them in a separate PR #57,  because I was not sure if this is intentional, ad may not be considered a bug, while I'm confident the differing event types are a bug.

**Comment by alfonsogarciacaro** [comment]
Fable.Browser.Dom 2.2.1 published with the fix, thanks again @kodfodrasz!
