### ISSUE TITLE
What namespace to open?

### ISSUE THREAD

**Issue by pkese** [fable-compiler/fable-browser#59]
It's really hard to find the information what namespace or module to open.

I've added nuget package Fable.Browser.Dom, but can't open anything.

![image](https://user-images.githubusercontent.com/278492/113330991-ae271c00-931f-11eb-9c7c-231a4e8275c4.png)

Could someone please add at least a single line into README to explain what goes where ...

**Comment by alfonsogarciacaro** [comment]
You're right, we tried to make it intuitive but we should have added the instructions anyways, sorry! 😅 I've updated the README: https://github.com/fable-compiler/fable-browser#usage

However, I don't understand the problem with `open Browser` in your capture. Does it still happen after running `dotnet restore` and restarting the IDE?

**Comment by pkese** [comment]
In the end I found that what worked was either:
```fsharp
open Fable.Import
let document = Browser.Dom.document
```
or explicitly opening Fable before Browser
```fsharp
open Fable
open Browser
let document = Dom.document
```

**Comment by pkese** [comment]
Sorry, it had to be something else.  
Suddenly it started working (it was consistently failing even with dotnet restore and restarting the IDE).  

Initially what worked was:

```fsharp
open Fable.Import
let document = Browser.Dom.document
```  
But then after that I managed to compile the code and then suddenly everything started working, even just `open Browser`.

I appologize for the report (it was probably Ionide caching some old stuff from before updating packages).

But thanks for the effort of adding that to README - at least now I know what is supposed to work and then search for problems only on the side of the IDE (in case this ever happens again).

**Comment by alfonsogarciacaro** [comment]
No worries! It's good you reminded me we should put this in the README, it will also help other users. I'm glad you got it working :) Btw, the Fable.Import namespace is deprecated, so in principle you shouldn't need to open it, please see https://fable.io/blog/Announcing-2-2.html
