### ISSUE TITLE
Missing SVGElement definition

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-browser#6]
`Fable.Leaflet` needs access to `SVGElement` but I can't find the definition of this type in the new packages.

**Comment by alfonsogarciacaro** [comment]
To make the Fable.Browser.Dom package smaller I removed all the [SVG-related types](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model#SVG_interfaces) and I was planning to put them in a different package. It'd be great if someone could help with that. For now, maybe you can just add your own definition of SVGElement directly to Fable.Leaflet?

**Comment by MangelMaxime** [comment]
Sure, I wanted to track this "problem".

I will probably do it after F# Exchange I am trying to release Thoth.Json and Thoth.Json.Net before F# Exchange
