### ISSUE TITLE
PermissionDescriptor throws  `error FABLE: Cannot find Browser.Types.PermissionDescriptor constructor`

### ISSUE THREAD

**Issue by MNie** [fable-compiler/fable-browser#67]
When trying to use a `navigator.permissions.query({ name = PermissionName.ClipboardRead; userVisibleOnly = false; sysex = false })` I got following error:

```
 error FABLE: Cannot find Browser.Types.PermissionDescriptor constructor
```

It seems that generated javascript looks like this:

```javascript
navigator.permissions.query(new null("clipboard-read", false, false));
```

But when I try to use it from [Fable.io](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChcDaAPAMoAuWAlhAOYCiEArgLYDcUASmAI6OU4BFRnCSUAZpTAATAIIBjOWADOSgHwBdXGQCe4KAAUwWZpRWVgEcnDJgoAXlxQnUAD5QA4ljgQbUx87cAEUhJP2dXAyxgZhAyfGIZJCRgAHcAOUYkgBlKGy8kDS1dW0NjUyVzSzJrRiV7fydEJQo4OTIoZuswAC4DIxMzCysbBqgmlraO6rJa3tKBiqHpvHDxr0mLOQALbxoeqAAKAHI4KABaVSgjgHlGMgBKKBTcrag9sgAaDrA4wlIKaj0JjMA7oOBKMAcTLKVAAaTACEQYIh93YXF4-DAQhE4lC8kUKkKOj083KlTScGYtgc4Tc7jAwGScmslVGbjSwDIuOZXIsSjZBlqWwFAFlKFJKAKwVSvKLKHIoiAthYVgEoCRwHAANZGEhgFBtVm0qDBABu8rAAEkIGJgAKAEKtLU0KKMCBSGA-bYOp0u4BuqQkbQQOQOpCMH7ATnC42lCrNSBkcjYOB7AUyZgISQ+HI0LZJyBKbDphT6ozRH5GAXubRRJRyUCqpxuEWpiCRql5KWiEAIYBwLBSLhwMJq9A9vsDqQAdSoI2NgVMICQcG0YNijBwArSMHQ+GJJX6ZIswXrVFi2HsUAA3qMIJT9qTBhAKVTRrUjAA1UyUZBga4QEg2i9H2jKjEo2gQgAHiBUZILgAC++7FH0ZTPnUNLOGsrTtLwRjAYcT6LBAp4KpQF5YOclwAFIkKg+hRAMYBEERlTDLUqj3KMAD03FQAAKtcgTXF8cibjgPhAVAECch0jAgCA2C+FA1BjBA2hQAgUQpBCWC9Nhkw4HhzS9G6uRUVAZlxOEvECUJIlQGJWASWQUkye0SjyYpWDKap3gaVpqS6fpCDNOs7RGRGzSJEgpkQOZFyWfFvwHlAFLmjQ1iXphjShRM7TgGhxFKHMR7ofgjbQPa2m6ag-HFPyfwyHcwDXOAECFMwwBSNCaVwBlWWUTlUAoO0xDuMkiIFOo0n9ZQmVkNgvTpfNg1XgAVkoFJcqaeC4KNUBSFe94DYtWCoIVCyVEoqB4Vg2gHNe95UlerEWK+aDjuRk6DsOUjsB+WDfhUf4AVJdhQBQEbsBB0FXlDtgIVxUioAABqjZBbJA6MHGIbpQAA+hZABEUjSOTxP3EAA&html=Q&css=Q) it seems that the proper javascript was generated:

```javascript
import { Record } from "fable-library/Types.js";
import { record_type, bool_type, string_type } from "fable-library/Reflection.js";

export class PermissionDescriptor extends Record {
    constructor(name, userVisibleOnly, sysex) {
        super();
        this.name = name;
        this.userVisibleOnly = userVisibleOnly;
        this.sysex = sysex;
    }
}

export function PermissionDescriptor$reflection() {
    return record_type("Test.PermissionDescriptor", [], PermissionDescriptor, () => [["name", string_type], ["userVisibleOnly", bool_type], ["sysex", bool_type]]);
}

export const d = navigator.permissions.query(new PermissionDescriptor("clipboard-read", true, true));
```

I'm using Fable 3.1.15. Maybe the PermissionDescriptor should be defined in a different way?

Here is how the definition looks like in `libdom.d.ts`:

```javascript
interface PermissionDescriptor {
    name: PermissionName;
}
```

**Comment by MangelMaxime** [comment]
Hello @MNie,

I released a new version of `Fable.Browser.Navigator` can you please give a try to v2.0.0

I think that the problem is that the binding was using a record to map the `PermissionDescriptor` but because `Fable.Browser.Navigator` is a pure binding we don't include the F# source file so Fable can't generate the type `PermissionDescriptor`.

In order, to use the new version of `PermissionDescriptor` you need to use `createEmpty` or `jsOptions` like that:

```fs
open Fable.Core.JsInterop

let myPermission = createEmpty<PermissionDescriptor>
myPermission.name <- // ...

//or
let myPermission = jsOptions<PermissionDescriptor>(fun o ->
   o.name <- // ...
)
```

Documentation can be found [here](https://fable.io/docs/communicate/js-from-fable.html#Plain-Old-JavaScript-Objects)

**Comment by MNie** [comment]
@MangelMaxime I believe it should be rather:

```fsharp
[<AllowNullLiteral>]
type PermissionDescriptor =
    abstract name: PermissionName with get, set
    abstract userVisibleOnly: bool with get, set
    abstract sysex: bool with get, set
```

rather than:

```fsharp
[<AllowNullLiteral>]
type PermissionDescriptor =
    abstract name: PermissionName
    abstract userVisibleOnly: bool
    abstract sysex: bool
```

in your [commit](https://github.com/fable-compiler/fable-browser/commit/bbdda6ce863a4f18cdfecf18dc198581baf91ddd)(?)

Right now I received the following error no matter if I use `jsOptions` or `createEmpty`.

```javascript
 error FSHARP: Property 'name' cannot be set (code 810)
 ```

**Comment by MangelMaxime** [comment]
Oops, my bad I wanted to make a quick release and didn't test it..
