### ISSUE TITLE
WebStorage API should use `DOMString`

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/fable-browser#7]
According to [MDN](https://developer.mozilla.org/fr/docs/Web/API/Storage/getItem) the WebStorage API works with `DOMString`.

The API contained under `Fable.Browser.WebStorage` use sometimes `obj` or `string`.

Using `string` is less problematic however using `obj` leads to some unexpected behaviour.

```fs
    let isActive =
        let storageValue = WebStorage.localStorage.getItem("admin_mode") // This is an obj 
        if isNull storageValue then
            false // This returns a bool
        else
            storageValue :?> bool // This returns a string at runtime which then lead to subtle bugs
```

Is there any reason to not binding to `DOMString`?

**Comment by alfonsogarciacaro** [comment]
Don't remember. As far as I know, we just use `string` to represent `DOMString` most of the times, so I guess we can use it here too.

**Comment by MangelMaxime** [comment]
Yes it seems like [DOMString](https://developer.mozilla.org/en-US/docs/Web/API/DOMString) is kind of an alias to `String` from the browser perspective.

I will just fix the binding definition then.
