### ISSUE TITLE
API generates invalid IL

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/fable-browser#78]
See https://github.com/dotnet/linker/issues/2281#issuecomment-928155925

The following code in [Browser.Dom.fs](https://github.com/fable-compiler/fable-browser/blob/36faa2e689fb8ea34ce91f73d08a9dc5630b3316/src/Dom/Browser.Dom.fs#L1056) generates invalid IL:

```fsharp
type [<AllowNullLiteral>] GlobalEventHandlers =
    abstract onpointercancel: (PointerEvent -> 'Out) with get, set
    abstract onpointerdown: (PointerEvent -> 'Out) with get, set
    abstract onpointerenter: (PointerEvent -> 'Out) with get, set
    abstract onpointerleave: (PointerEvent -> 'Out) with get, set
    abstract onpointermove: (PointerEvent -> 'Out) with get, set
    abstract onpointerout: (PointerEvent -> 'Out) with get, set
    abstract onpointerover: (PointerEvent -> 'Out) with get, set
    abstract onpointerup: (PointerEvent -> 'Out) with get, set
    abstract onwheel: (WheelEvent -> 'Out) with get, set
```

In this context, the type parameter ``'Out`` is meaningless. This is not supposed to be valid F#; the compiler is only allowing it due to a bug. When this gets fixed in FSC, this code (and any other code like it) will generate compiler errors.

**Comment by alfonsogarciacaro** [comment]
I've published new versions of the affected packages 👍
