### ISSUE TITLE
nextElementSibling and previousElementSibling Not implemented

### ISSUE THREAD

**Issue by dredgy** [fable-compiler/fable-browser#86]
### Description

On elements, nextElementSibling and previousElementSibling do not seem to be defined.

### Repro code
https://fable.io/repl/#?code=LYewJgrgNgpgBAUVsGA7ALgKEyADmuAZQE8BndGYHfVOAIQCcQB3UmBgOgBVj9TqCAMQCGAI1gcAwiAYwBtRizacAIiCp4Ci1uymlSCAB4VUpAJYhT8uIMIALYQ1xSZc7LHRwYyNJ4C8cGAgAMYQKBgcAI4Q7MSE3jDB6DJwAES4qZjBlqQgElAgAOYAFAnh6ByoMMZIlL6EZuJmqIUAlEA&html=DwBwfMD04LAFDAM4gIYDsKWesQ&css=Q

### Expected and actual results

When given a Node, .nextElementSibling should return the next sibling that is also an element. Same with previousElementSibling

**Comment by dredgy** [comment]
Couldn't figure out how to push a branch without getting rejected, but is a simple abstract method to add under Node.

**Comment by MangelMaxime** [comment]
> Couldn't figure out how to push a branch without getting rejected, but is a simple abstract method to add under Node.

You can't push directly into this repository, you need to create a fork of it under your name by clicking "Fork" at the top of the page.

Then you can push the changes to your fork and then create a Pull Request between your fork and this repository.

**Comment by alfonsogarciacaro** [comment]
I think Github automatically creates the fork for you if you click the Edit button (the pencil icon).
