### ISSUE TITLE
Is there an object for screen orientation?

### ISSUE THREAD

**Issue by sumeetdas** [fable-compiler/fable-browser#89]
Hello! I'm trying to add [screen orientation event listener](https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/onchange) but I couldn't find any object like `screen.orientation` in the library. Is it available in this library with a different name or in some other library (like Feliz)?

**Comment by alfonsogarciacaro** [comment]
If the API is new probably we're just missing it. If the API is big we put it in a different package so Browser.Dom.fs doesn't become too bloated, but I guess for this one we can add it to Browser.Dom directly. Would you like to try a PR?

BTW, as a temporary solution, you can add it to your project using extensions:

```fsharp
open Fable.Core
open Browser.Types

type [<AllowNullLiteral>] ScreenOrientation =
    inherit EventTarget
    abstract ``type``: string // TODO: StringEnum
    abstract angle: ushort
    abstract onchange: (Event -> unit) with get, set
    abstract lock: unit -> JS.Promise<unit>
    abstract unlock: unit -> unit

type Screen with
    [<Emit("$0.orientation")>]
    member _.orientation: ScreenOrientation = jsNative
```

**Comment by sumeetdas** [comment]
I'll add a PR for this one. This will take some time because I'm new to F# and Fable compiler.

**Comment by sumeetdas** [comment]
I've raised a PR to add `orientation`: https://github.com/fable-compiler/fable-browser/pull/90

**Comment by alfonsogarciacaro** [comment]
Thanks @sumeetdas! I've pushed the new version 👍
