### ISSUE TITLE
encodeURIComponent

### ISSUE THREAD

**Issue by AlbertoDePena** [fable-compiler/fable-browser#98]
Not sure why but I can't see `window.encodeURIComponent`. I see it in the source code `Browser.Dom.fs` but not available in IntelliSense

**Comment by alfonsogarciacaro** [comment]
That's strange, do you use it like this?

```
// open Browser.Types to access types defined in the Fable.Browser.XXX libraries (like HTMLInputElement)
open Browser.Types

// open Browser to access global values declared by the Fable.Browser.XXX libraries
open Browser

window.encodeUri(uri)
```

BTW, `encodeUri` is also defined in Fable.Core.JS. I usually use it like this:

```
open Fable.Core

JS.encodeUri(uri)
```

**Comment by AlbertoDePena** [comment]
@MangelMaxime 

I am using the latest non-prerelease version =)

**Comment by MangelMaxime** [comment]
This is really strange:

![image](https://user-images.githubusercontent.com/4760796/171655404-39de58be-506a-4c49-a555-2e027f4adb99.png)

I am using Fable.Browser.Dom (2.10) in the screenshot above and it is working.

Gitpod VM: https://gitpod.io/start/#mangelmaxim-templategit-o1dm3mvev4c

**Comment by MangelMaxime** [comment]
I am closing this issue because the API should be available according to the tests.

Please re-open it if you still have the problem
